spring.application.name=backend-ecommerce-grupo-innovar

server.port=8080

# =========================
# DATABASE (DEV / LOCAL)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# =========================
# FRONTEND
# =========================
app.frontend.url=${FRONTEND_URL:http://localhost:4200}
app.base-url=${BASE_URL:http://localhost:8080}

# =========================
# WOMPI
# =========================
wompi.public-key=${WOMPI_PUBLIC}
wompi.private-key=${WOMPI_PRIVATE}
wompi.url=https://sandbox.wompi.co
wompi.integrity-secret=${WOMPI_INTEGRITY}