spring.application.name=backend-ecommerce-grupo-innovar
server.port=${PORT:8080}

# =========================
# DATABASE (PROD)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# =========================
# FRONTEND / BASE URL
# =========================
app.frontend.url=${FRONTEND_URL}
app.base-url=${BASE_URL}

# =========================
# WOMPI
# =========================
wompi.public-key=${WOMPI_PUBLIC}
wompi.private-key=${WOMPI_PRIVATE}
wompi.url=https://sandbox.wompi.co
wompi.integrity-secret=${WOMPI_INTEGRITY}

# =========================
# EMAIL (SMTP GMAIL)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true