spring.application.name=backend-ecommerce-grupo-innovar

# Server
server.port=8080

# SQL Server - ajusta según tu instancia
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=DB#2025*Star8
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIG
app.jwt.secret=HG73js8Hs92JskA91ksla88nQpqLkWmZZz9HssKqQw=
app.jwt.expiration-ms=86400000

# Frontend CORS (ajusta al host dev)
app.frontend.url=http://localhost:4200

# Wompi Configuración
wompi.public-key=pub_test_j8eHF4Xk10doJo7WN9kZlhXtnPa9OtNU
wompi.private-key=prv_test_FgizgPN8nPLFBvGLTN70EiQXVn5a2HhH
wompi.url=https://sandbox.wompi.co
wompi.integrity-secret=test_integrity_PxYh5aSuKWU116aQdpIbBNe144LHRSHi

# Application Base URL
app.base-url=http://localhost:8080